locations:
  default:
    city: Lille
    latitude: 50.62925
    longitude: 3.057256

mails:
  default:
    from: baptiste@nomadoffice.co



price_share:
  vat: 19.6
  company: 0.85
  nomad_office: 0.15
