clean_unavailability_daily:
  cron: "* * * * *"
  # cron: "20 0 * * *" # everyday at 12:20am
  class: CleanOldUnavailabilitiesJob
  description: "clean old unavailabilities"

link_with_calendar_every_10_minutes:
  # cron: "10 * * * *" # every 10 minutes
  cron: "* * * * *"
  class: UpdateCalendarJob
  description: "link calendar data to unavailabilities"
